/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: adbedc595dbca9861a8de975fa31979e)
interface __BaseEnv_Env {
	SESSION_ATTEMPT_LIMITER: RateLimit;
	OPENAI_PROJECT: string;
	OPENAI_BASE_URL: string;
	AGENTS_ENVIRONMENT_TYPE: string;
	OPENAI_API_KEY: string;
	SESSION_AUTH_SECRET: string;
	GLOBAL_SESSION_LIMITER: DurableObjectNamespace<import("./src/index").GlobalSessionLimiter>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "GlobalSessionLimiter";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_PROJECT" | "OPENAI_BASE_URL" | "AGENTS_ENVIRONMENT_TYPE" | "OPENAI_API_KEY" | "SESSION_AUTH_SECRET">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}